name: update dependencies
on:

  schedule:
    - cron:  '0 0 1 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: development

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.10'
          cache: pip

      - name: Install pre-commit and pip-tools
        run: pip install pre-commit pip-tools

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Run pip-compile
        run: pip-compile --upgrade

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          committer_username: 'p-galligan'
          pull_request_branch: 'dependency-updates'
          pull_request_title: 'Dependency Updates'